language: rust
rust:
  - nightly
env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib
install:
  # SDL2, SDL2_image, and SDL2_ttf
  - curl -O http://www.libsdl.org/release/SDL2-2.0.0.tar.gz
  - curl -O https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz
  - curl -O https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz
  - tar -xzvf SDL2-2.0.0.tar.gz
  - tar -xzvf SDL2_image-2.0.1.tar.gz
  - tar -xzvf SDL2_ttf-2.0.14.tar.gz
  - (cd SDL2-2.0.0 && ./configure && make && sudo make install)
  - (cd SDL2_image-2.0.1 && ./configure && make && sudo make install)
  - (cd SDL2_ttf-2.0.14 && ./configure && make && sudo make install)
