[package]
name = "trage"
version = "0.1.0"
authors = ["Darin Minamoto <darinm223@gmail.com>"]
description = "A work in progress rage 2d platformer game that only uses SDL"
readme = "README.md"

[dependencies.game]
path = "./src/game"
