[package]
name = "mold2d"
version = "0.0.1"
authors = ["Darin Minamoto <darinm223@gmail.com>"]
description = "A work in progress 2d platformer game and game engine that only uses SDL"
repository = "https://github.com/DarinM223/mold2d"
readme = "README.md"

[dependencies]
libc = "0.2"
sdl2 = "0.9"
sdl2_image = "0.3"
sdl2_ttf = "0.9"
