[package]
name = "trage"
version = "0.1.0"
authors = ["Darin Minamoto <darinm223@gmail.com>"]
description = "A work in progress rage 2d platformer game that only uses SDL"
readme = "README.md"

[dependencies]
sdl2 = "0.9"
sdl2_image = "0.3"
sdl2_ttf = "0.9"
rand = "0.3"
clippy = { version = "*", optional = true }

[dependencies.sorty]
git = "https://github.com/Wafflespeanut/rust-sorty"

