[package]
name = "mold2d"
version = "0.0.2"
authors = ["Darin Minamoto <darinm223@gmail.com>"]
description = "A simple platformer game library in Rust"
repository = "https://github.com/DarinM223/mold2d"
readme = "README.md"
keywords = ["game", "library", "actors"]
license = "MIT"

[dependencies]
libc = "0.2"
sdl2 = "0.9"
sdl2_image = "0.3"
sdl2_ttf = "0.9"

[lib]
doctest = false
