array_layout = "Visual"
chain_indent = "Block"
array_width = 80
chain_one_line_max = 80
comment_width = 80
condense_wildcard_suffices = false
closure_block_indent_threshold = 2
control_brace_style = "AlwaysSameLine"
disable_all_formatting = false
error_on_line_overflow = true
fn_args_density = "Tall"
fn_args_layout = "Visual"
fn_args_paren_newline = true
fn_brace_style = "SameLineWhere"
fn_call_style = "Visual"
fn_call_width = 80
fn_empty_single_line = false
fn_return_indent = "WithArgs"
fn_single_line = false
force_explicit_abi = true
force_format_strings = false
format_strings = true
generics_indent = "Visual"
hard_tabs = false
impl_empty_single_line = false
indent_match_arms = true
item_brace_style = "SameLineWhere"
match_block_trailing_comma = false
max_width = 100
newline_style = "Unix"
normalize_comments = false
reorder_imported_names = false
reorder_imports = false
single_line_if_else_max_width = 50
skip_children = false
space_after_bound_colon = true
space_after_type_annotation_colon = true
space_before_bound = false
space_before_type_annotation = false
spaces_around_ranges = false
spaces_within_angle_brackets = false
spaces_within_parens = false
spaces_within_square_brackets = false
struct_lit_multiline_style = "PreferSingle"
struct_lit_style = "Block"
struct_lit_width = 35
struct_variant_width = 35
tab_spaces = 4
take_source_hints = false
trailing_comma = "Vertical"
type_punctuation_density = "Wide"
use_try_shorthand = false
where_density = "CompressedIfEmpty"
where_layout = "Vertical"
where_pred_indent = "Visual"
where_style = "Default"
wrap_comments = false
wrap_match_arms = true
write_mode = "Replace"
